// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPm5bfY9Y5jWdWhDCaZBWfaIiQtSkOpWQ',
    appId: '1:922343828558:web:1478782c6af9a2f6ae271f',
    messagingSenderId: '922343828558',
    projectId: 'fb-auth-bloc-auth',
    authDomain: 'fb-auth-bloc-auth.firebaseapp.com',
    storageBucket: 'fb-auth-bloc-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJHDw0wOXUeSKZSzeFdn_xz4H3ToMsUHw',
    appId: '1:922343828558:android:913d2f5ce7a42709ae271f',
    messagingSenderId: '922343828558',
    projectId: 'fb-auth-bloc-auth',
    storageBucket: 'fb-auth-bloc-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmKvToU1XPNMKrTKvnjkUHHHow06p08KU',
    appId: '1:922343828558:ios:4d5cc20883a4b367ae271f',
    messagingSenderId: '922343828558',
    projectId: 'fb-auth-bloc-auth',
    storageBucket: 'fb-auth-bloc-auth.appspot.com',
    iosClientId: '922343828558-7f7v537qiupshgntisgsdm3umhliu7tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.videalpha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmKvToU1XPNMKrTKvnjkUHHHow06p08KU',
    appId: '1:922343828558:ios:4d5cc20883a4b367ae271f',
    messagingSenderId: '922343828558',
    projectId: 'fb-auth-bloc-auth',
    storageBucket: 'fb-auth-bloc-auth.appspot.com',
    iosClientId: '922343828558-7f7v537qiupshgntisgsdm3umhliu7tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.videalpha',
  );
}
